### ISSUE TITLE
process stopped when meet incomplete localized interface files

### ISSUE THREAD

**Issue by rockingdice** [Flinesoft/BartyCrouch#105] opened 2018-08-01 14:21 UTC
My situation is:
Cached.storyboard (4 localized strings files)
LaunchScreen.storyboard (1 localized strings file)
Main.storyboard (4 localized strings files)

Because there' no need to localize a launch screen, I removed all strings for it except English. After doing that, the process interrupts after processing LaunchScreen.storyboard, it gives error:

`No file exists at output path ja.lproj/LaunchScreen.strings` 

And Main.storyboard is not processed anymore.

After I added the other 3 language strings for LaunchScreen.storyboard, it works like usual.

I think this situation is not rare and should be continued to do the rest of work.

**Comment by Dschee** [comment] 2018-08-02 08:42
Thank you @rockingdice for reporting this issue. I came across this issue myself a few times, at the first moment I also thought "no, this must be fixed!". But the way I solve this issue is not by adding the missing languages – instead I make the Storyboard non-localized, which IMHO ist the more correct thing to do here (I mean, why should you keep a non-localized file localized anyways).

So, you might also want to do that – unfortunately there's no button to click in Xcode, you'd have to do it manually like described [here](https://stackoverflow.com/a/42256341).

Having that said, we could still fix the issue in BartyCrouch, though the question for me is: Isn't this actually a feature? I mean, BartyCrouch is making sure that – if I localize a Storyboard – that I don't forget any language. This is not by design, but it's a nice side-effect that some might have even learned to trust on, so I'm not sure if we should turn off this feature. We could also just improve the warning instead so people who are coming across this know how to fix this properly.

But I'm not decided yet, so I'm looking forward to hear other opinions.

**Comment by rockingdice** [comment] 2018-08-03 08:10
@Dschee Agreed. Thanks for your info, it helped me a lot. What you said is important, do it in the right way. I didn't notice the localization problem until this.

**Comment by seboslaw** [comment] 2018-11-20 17:16
I'd like to weigh in here. I currently have a project with multiple targets out of which some support e.g. Italian, while others aren't. 
The problem is that Xcode will only let you add localisation on a per-project basis. So I added 'Italian' to the Localizations of the entire project. However, as said only a few of my targets have their storyboards localised in Italian. The storyboards of the other targets have italian 'unchecked'.

**Comment by Dschee** [comment] 2018-11-30 14:48
@seboslaw Okay, I see, the wish to be able to turn this off is there. So I'll try to work this into the next major release of BartyCrouch. But I'm curious, what your setup is, cause I'm wondering why you have a language for specific Storyboards but not for the others – and that in the same project ... if it was two different Apps, I think two different projects would make more sense. So it would be great to hear what your reasons are!

**Comment by Dschee** [comment] 2019-03-26 12:26
Please note that this was probably fixed via #114 – if the issue still exists with Version 4 of BartyCrouch, feel free to comment and I'l reopen.

**Closed by Dschee** 2019-03-26 12:26 UTC
