### ISSUE TITLE
Error! No `Localizable.strings` file found for output.

### ISSUE THREAD

**Issue by derick182** [Flinesoft/BartyCrouch#27] opened 2016-07-02 08:01 UTC
Hi, 
i cannot make "code" command work.
I tried both from build script and from terminal.

Code from build script gives me no error but code is not working (while interface works properly): 
```
if which bartycrouch > /dev/null; then
bartycrouch interfaces -p "$PROJECT_DIR"
bartycrouch code -p "$PROJECT_DIR" -l "$PROJECT_DIR" -a
else
echo "warning: BartyCrouch not installed, download it from https://github.com/Flinesoft/BartyCrouch"
fi
```

and from terminal I open a new terminal inside the folder containing my code files and my *.lproj folders and write:
`bartycrouch code -p "/" -l "/" -a`
here terminal writes 

> Error! No `Localizable.strings` file found for output.

The only way to make "code" working is open a new terminal inside one of my *lproj folder and then `bartycrouch code -p "../" -l "../" -a`

Thank's for Your help

**Comment by Dschee** [comment] 2016-07-02 09:11
Hi @derick182, thank you for your issue report.

I'm closing this as it's a duplicate of #11 – please keep discussion to that issue so we don't have to search all over the place to discuss one topic. I'm also reopening it since people still seem to face this problem. Please see my comments on that thread, they should help you fix this issue.

**Closed by Dschee** 2016-07-02 09:11 UTC
