### ISSUE TITLE
Error! No file exists at output path '<path><file>.strings'.

### ISSUE THREAD

**Issue by superandrew** [Flinesoft/BartyCrouch#64] opened 2017-08-18 07:53 UTC
I'm honestly having a hard time understanding why I have this error. I have a Storyboard localized in base + 1 language, Then I have a Localizable.strings file for the NSLocalizedString(s) in code (which I performed using in swift a ".localized" extension to String).
Here's the storyboard with its .strings file localized in italian
![screen shot 2017-08-18 at 09 50 46](https://user-images.githubusercontent.com/71364/29449401-e517759e-83fa-11e7-9e45-1ab933ac8290.jpg)
here some other xib localized (some using .strings some using localized .xib)
![screen shot 2017-08-18 at 09 50 53](https://user-images.githubusercontent.com/71364/29449402-e90a1fee-83fa-11e7-9f82-c9f5869e1e26.jpg)

I have this error: 
```
$ nowr-ios (master) $ bartycrouch interfaces -p .
BartyCrouch: Successfully updated strings file(s) of Storyboard or XIB file.
Error! No file exists at output path './nowr-ios/Code/it.lproj/LoginViewController.strings'.
```

Am I missing something obvious or is there a bug?

**Comment by Dschee** [comment] 2017-08-18 19:36
Thank you for reporting the issue @superandrew. I can see a few potential problems from your screenshots:

1. Your `nowr-LaunchScreen.storyboard` is not localized in Italian (`nowr-LaunchScreen.strings` is missing in `it.lproj`
2. `LoginViewController.xib` is not String-localized, meaning in `it.lproj` there should be a `LoginViewController.strings` file instead of a .xib file
3. Same is true for `SignupViewController.xib`

Please make sure you always localize all localizable files in all the languages you support in your project. Otherwise BartyCrouch might not work as expected. If you don't need to localize a Storyboard (like the nowr-LaunchScreen) then you should simply unlocalize the screen entirely so it doesn't appear even in `Base.lproj`.

**Comment by Dschee** [comment] 2017-09-26 10:20
I'm closing this due to inactivity.

**Comment by tirrorex** [comment] 2017-10-09 13:00
You should add that to the documentation imo (the fact that if we don't localize we need the storyboard in dev language not base langauge).

**Comment by tirrorex** [comment] 2017-10-17 12:03
"Please make sure you always localize all localizable files in all the languages you support in your project. Otherwise BartyCrouch might not work as expected. If you don't need to localize a Storyboard (like the nowr-LaunchScreen) then you should simply unlocalize the screen entirely so it doesn't appear even in Base.lproj."

This should be in the documentation

**Comment by Dschee** [comment] 2017-10-17 12:35
Thank you @tirrorex for the text. That's not exactly a PR but I've included it into the README nearly as is (just removed the "nowr-" in front of "LaunchScreen") via 3b5b08490902f0756b3d6b37f951fc98b974f653.

**Comment by jameshays** [comment] 2018-10-08 17:05
Alright, I know this is closed and old, but a nice addition would be to generate the file that is missing.  I know, PRs are always welcome. :)

**Comment by Dschee** [comment] 2018-10-09 08:43
Alright, reopening. ;)

**Comment by Dschee** [comment] 2019-07-29 10:31
Is this still an issue with version 4? I feel like I tackled this in #114. So closing for now until someone reports otherwise.

**Closed by Dschee** 2019-07-29 10:31 UTC

**Comment by thejeff77** [comment] 2019-12-31 04:59
I'm seeing this currently. If you go to the base project and remove a localization, and bartycrouch runs the build script outlined in the documentation, it still tries to find that localization. Not sure why that is but it would be awesome if someone could fix this!

**Comment by Jeehut** [comment] 2019-12-31 08:52
@thejeff77 Thank you for reporting this. Can you please give me some further information to understand the problem better:

1. What do you mean by "go to the base project"? Do you mean the `Base.lproj` directory? Or do you mean a target in Xcode where you remove a language?
2. How do you know that BartyCrouch is trying to find that localization still? Can you try to run the two commands from the build script manually and give me the full output?

**Comment by thejeff77** [comment] 2020-01-03 17:56
Hey there, thanks for the quick reply!

I'll keep this notification email unread and reply again with error messages next time I enable the bartycrouch update in my build scripts. 

For now, to unblock the story, I'll give you what I can right now:

What do you mean by "go to the base project"? -> Your second answer is correct: "... a target in Xcode where you remove a language"

Yeah its the top level target with the xcode icon on it - where you set supported languages for the whole project.

How do you know that BartyCrouch is trying to find that localization still?

After clearing all Derived Data, clearing the Project Data, restarting XCode, rebuilding, deleting & re-installing the app, I still received an error about the removed language not found by bartycrouch from the "bartycrouch update -x" command in the run script phase of the build.  

Can you try to run the two commands from the build script manually and give me the full output?

Yes. Stay tuned. For now you should have enough info to see if it is reproducible and unblock the bug. I'm curious if you see the same behavior!

Thanks, and let me know if you have any additional questions.

**Comment by thejeff77** [comment] 2020-01-05 17:30
Turns out removing that localization from the main target doesn't delete the folder. 

If the folder isn't deleted, bartycrouch won't ignore it. In my case it was vi.lproj

Might be something to take a look at? I.E. check the target languages instead of the physical file system - as the master of the languages is the target, not the filesystem.
