### ISSUE TITLE
Localized Info.plist files are wiped

### ISSUE THREAD

**Issue by magneticrob** [Flinesoft/BartyCrouch#136] opened 2019-07-25 11:09 UTC
Hey, I have just localized my Info.plist file, which requires creating a strings file called "InfoPlist.strings", clicking the localize button in Xcode, then filling it with strings in the corresponding languages in the following format:

`NSCalendarsUsageDescription = "This allows us to save the appointments you make.";`

Localization works correctly. Note that the key does not have quotes marks around it. If you run the BartyCrouch script as part of your build phases, these files are wiped.

This breaks the localization. I can have a look at this in depth when I have time, but in the meantime I have had to remove BartyCrouch from my project, if anyone is around to have a look I'd really appreciate it!

**Comment by magneticrob** [comment] 2019-07-25 11:32
Just had a quick look at the repo and it looks like at some point perhaps an attempt was made to handle this situation, see here: https://github.com/Flinesoft/BartyCrouch/blob/b651fb970616a9739834cd2e7837e446b4786437/Sources/BartyCrouchKit/FileHandling/StringsFilesSearch.swift#L14

Although we declare a reference to the file as we should be avoiding it ("blacklistedStringFileNames"), it doesn't seem to actually be used anywhere

**Comment by Dschee** [comment] 2019-07-28 07:43
Thanks for reporting this, it sure looks like something went wrong. I hope we can easily reproduce and fix it. Will have a look soonish – but feel free to drop a PR if you get the chance to fix it yourself. We probably had the same problem somewhere and started to fix it, as you can see in the code above. But why didn't finish it, I don't know. Maybe we found a workaround?

Maybe @fredpi can give more insight here?

**Comment by fredpi** [comment] 2019-07-28 21:42
In a project of ours where we use BartyCrouch in conjunction with `Info.plist` Localizations, everything works fine – but I guess that's just because the `InfoPlist.strings` files are in a different folder (`"App/SupportingFiles"`) than the `Localizable.strings` files (`"App/Resources"`): A folder that's not parsed by BartyCrouch, as can be seen in the configuration.

### Configuration

Here's our `.bartycrouch.toml`:

```toml
[update]
tasks = ["interfaces", "transform", "normalize"]

[update.interfaces]
path = "App/Sources"

[update.transform]
codePath = "App/Sources"
localizablePath = "App/Resources"
transformer = "swiftgenStructured"
supportedLanguageEnumPath = "App/SupportingFiles"

[update.normalize]
path = "App"
sourceLocale = "de"

[lint]
path = "App"
```

### Workaround

Of course this issue should be fixed soon, but in the meantime you can probably work around it by moving the localizations into a folder that's not configured to be parsed by BartyCrouch.

**Comment by lveecode** [comment] 2019-08-20 15:39
Hi. Looks like the problem persists.
Of note: I have installed barty crouch for the first time a week ago, after the fix was merged, but bartycrouch reports it's version as 4.0.0 even though the latest (and the one brew claims to have installed) is 4.0.2

Before `bartycrouch update`:
![before](https://user-images.githubusercontent.com/15900746/63360264-bc0c7100-c376-11e9-8b11-c768d3eca1ab.jpg)

After:
![after](https://user-images.githubusercontent.com/15900746/63360281-c4fd4280-c376-11e9-9e7e-94eba3a921d0.jpg)

This happens with default `bartycrouch.toml` generated by `bartycrouch init`

Version discrepancy:
![version](https://user-images.githubusercontent.com/15900746/63361886-a2205d80-c379-11e9-8836-7b77ab2ac7d7.jpg)

**Comment by nonpensavo** [comment] 2020-02-02 03:23
> Hi. Looks like the problem persists.
> Of note: I have installed barty crouch for the first time a week ago, after the fix was merged, but bartycrouch reports it's version as 4.0.0 even though the latest (and the one brew claims to have installed) is 4.0.2

Any workarounds? I tried brew and mint, version also shows 4.0.0 although installing 4.0.2
Gotta copy paste infoplists for all localizations every update command..

**Comment by Danbana** [comment] 2021-01-17 05:38
I am also having this issue.

I think this occurs when adding new Localized files (as described in the first post).

bartycrouch was working great, but now I've added two more Localizable-blah.strings files, and they are wiped out when I run bartycrouch. 

I really need a way to ignore these files, but I doubt bartycrouch should be wiping files like this...

**Comment by FlineDevPublic** [comment] 2022-01-14 16:07
Revisiting this topic again in my Friday Open Source [live stream](https://twitch.tv/jeehut), I think things have gone quite wrong here while trying to fix the original posters request. What they had said is this:

> `NSCalendarsUsageDescription = "This allows us to save the appointments you make.";`
> Localization works correctly. Note that **the key does not have quotes marks around it**. If you run the BartyCrouch script as part of your build phases, these files are wiped.

So the actual issue, I'm guessing now, was that the key didn't have "quote marks around it", which probably caused BartyCrouch's regexes to not recognize them as keys. That's probably why these keys were wiped. The actual fix probably would have been to just **add quote marks** around the key like this:

`"NSCalendarsUsageDescription" = "This allows us to save the appointments you make.";`

Then nothing should have been wiped. But because I missed that part back then and misunderstood some things, I actually excluded the Info.plist file from translated Strings files in https://github.com/Flinesoft/BartyCrouch/pull/138. But that was totally unnecessary and is now causing multiple other people to report that InfoPlist.strings files are not being updated by BartyCrouch (as in English language keys being added to other languages automatically, for example).

So, I think the best way to deal with this is to make the now "fixed" ignoring of the InfoPlist.strings file a configuration option so that everyone who doesn't want these files to be "updated" by BartyCrouch to exclude them, and those who want to just keep that option empty so every Strings file gets updated. I'll be keeping you updated.

**Closed** 2022-01-21 16:02 UTC
