### ISSUE TITLE
normalize doesn't sort Base Localizable.strings

### ISSUE THREAD

**Issue by liweihan** [Flinesoft/BartyCrouch#144] opened 2019-08-29 08:22 UTC
Hello there, thanks for this amazing project!

I noticed that Base Localizable.strings doesn't seem to be supported, is that by design? For example sortByKeys doesn't apply to Localizable.strings in Base.lproj.

[update.normalize]
path = "MyApp/Resources"
sourceLocale = "Base"
harmonizeWithSource = true
sortByKeys = true

Thanks!

**Comment by Dschee** [comment] 2019-08-30 20:24
Yes, that's by design. Actually there shouldn't be a `Localizable.strings` file within the `Base.lproj` folder in your project. It's only there for Storyboard and XIB files, at least that's how I always understood it. Correct me if I'm wrong.

I have seen in some projects, that a `Localizable.strings` file is accidentally placed there. But I usually just delete it without any disadvantages. What should it be for? I haven't seen any iPhone user, running his device in the language "Base", so it wouldn't ever be used AFAIK.

I hope this clarifies the issue. I'll close this as a non-issue until you prove me otherwise.

**Closed by Dschee** 2019-08-30 20:24 UTC

**Comment by liweihan** [comment] 2019-08-30 23:17
Base is meaningful for people that not using English as the default language. If a user preferred language is not in the list of supported language of the app, then it will fallback to Base ahead of English.

**Comment by Dschee** [comment] 2019-08-31 04:10
Can you point me to the documentation of this behavior?

**Comment by liweihan** [comment] 2019-08-31 23:50
Actually you are right, I can't find a way to let the Base stings show up. So yeah it was false statement.

**Comment by noah-nuebling** [comment] 2022-08-15 15:39
From [this Apple Documentation](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/InternationalizingYourUserInterface/InternationalizingYourUserInterface.html#//apple_ref/doc/uid/10000171i-CH3-SW2):

> ... Xcode modifies your project folder according to the selections you make in this dialog. Xcode creates a Base.lproj folder in your project folder and adds to it the resource files you select. **Xcode creates a language folder for the development language but only adds resources that need translation to the folder**. For example, if you select English as the development language, Xcode **inserts** the resource file in the Base.lproj project folder but **not the en.lproj folder because the resource is already in English**.

I'm new to localization and just throwing this out there, but wouldn't this suggest that you have the translation for the development language directly in the .xib/.storyboard files inside the Base.lproj folder?

I feel like that would make so much more sense from a workflow perspective as well. 

You build the interface files in a real language - the development language. And then any **further** languages you add via .strings files.

Instead of building the UI in some pseudo 'base' language, and then having the extra effort of translating from the pseudo language to the development language via a strings file.
