### ISSUE TITLE
dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib

### ISSUE THREAD

**Issue by EinSoldiatGott** [Flinesoft/BartyCrouch#179] opened 2020-04-18 16:38 UTC
Hi I'm having this issue:

```
dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
  Referenced from: /usr/local/bin/bartycrouch
  Reason: image not found
zsh: abort      bartycrouch init
```

I saw an issue reported here but its closed, in that one you said that we should install using brew. I installed BartyCrouch using brew since the beginning  following  the tutorial
https://medium.com/@mds6058/localization-in-ios-and-how-to-make-it-not-suck-3adcbc3ec08f

I'm using xcode 11.3.1 (I need this version, so installed Xcode manually, downloading the xip 11.3.1:/) is this the problem? Do I need 11.4? Or maybe the file locations?
I've MacOS Catalina 10.15.4

Thanks

**Comment by Jeehut** [comment] 2020-04-19 09:30
Hi @EinSoldiatGott, than you for reporting this issue.

In the latest versions (4.1.0+) we started requiring Xcode 11.4, so yes I think that that's the issue. I suggest that as long as you can't upgrade to Xcode 11.3, just use version 4.0.2. See [this post on SO](https://stackoverflow.com/a/4158763/3451975) on several options to do that (I think the easiest would be if you already had the previous version installed).

**Comment by hactar** [comment] 2020-04-19 19:17
I have this issue when I use Xcode 11.4 too if I open the project by double clicking the Packages.swift file. If I use `swift package generate-xcodeproj` from the command line to generate an xcodeproj, and open the project via this file, I can build and run correctly via Xcode.

**Comment by Jeehut** [comment] 2020-04-20 06:59
@hactar Can you provide a Demo project where this is happening?

**Comment by hactar** [comment] 2020-04-20 07:28
Reproduction Steps (tested with Xcode 11.4.1 on 10.15.4): 
- Clone the github repo
- Double click the Package.swift file, Xcode opens and and starts downloading the packages to build this project
- When download is done, switch the scheme to bartycrouch
- hit build and run.

Build completes, Xcode launches the app, but app fails to launch. As said: if you use swift package generate-xcodeproj (the "old" way of working with the swift package manager) all works correctly.

<img width="1703" alt="Screenshot 2020-04-20 at 09 26 05" src="https://user-images.githubusercontent.com/645674/79725278-441d8e80-82e9-11ea-9980-a10f9f0bc9ea.png">

**Comment by Jeehut** [comment] 2020-04-20 09:52
Ahh, @hactar what you're reporting happens when you checkout BartyCrouch itself. I see. It's happening for me, too, but only when I choose the `bartycrouch` scheme. I'm not sure if this can be fixed due to the way loading things works in SwiftPM generated projects. If you have an idea, please tell me about it. But for development I use the other schemes and tests instead. When I want to test things out in real projects, I run `swift build -c release` and use the tool under `.build/release/bartycrouch` with an absolute path specified in my test projects.

What definitely should be fixed though is what @EinSoldiatGott reported that this bug happens when BartyCrouch is installed via Homebrew. But I still think that's only happening on Xcode 11.3 or lower, not on Xcode 11.4. @EinSoldiatGott Have you tried if it fails with Xcode 11.4 as well? @hactar Do you see the same error when installing the latest version via Hombrew as well?

**Comment by hactar** [comment] 2020-04-20 09:57
Yes, I can confirm everything you say, the actual build via homebrew does work for me. I just added my comment because I stumbled across it when doing my PR and it matches the error message that @EinSoldiatGott sees.  I have no ideas of how to fix it.

**Comment by Jeehut** [comment] 2020-04-20 09:59
Okay, I'm strongly suspecting that to be an Xcode 11.3 issue which makes sense. So I will close this task then until proved differently (in which case I can repoen again).

**Comment by EinSoldiatGott** [comment] 2020-04-21 04:39
Hi, yes I can confirm that compiling from sources BartyCrouch 4.0.2 works ok with X code 11.3

Thanks for your work!

**Comment by tmolitor-stud-tu** [comment] 2020-11-16 02:13
For me (Xcode 12.2, MacOS 10.15.7) only this helped:
`install_name_tool --change @rpath/lib_InternalSwiftSyntaxParser.dylib /Applications/Xcode.app/Contents/Frameworks/lib_InternalSwiftSyntaxParser.dylib /usr/local/bin/bartycrouch`

**Comment by Sn0wfreezeDev** [comment] 2022-01-06 11:26
I rediscovered the issue again when installing through Hombrew and **not** having an App with the name Xcode.app in the Applications folder. After renaming Xcode_13_x to Xcode.app it works as expected

**Closed** 2022-02-21 09:43 UTC
Labels: question

**Comment by lewis-smith** [comment] 2022-03-12 16:35
`ln -s /Applications/Xcode-13.3.0-Release.Candidate.app/ /Applications/Xcode.app`
