### ISSUE TITLE
Custom function With different syntax

### ISSUE THREAD

**Issue by Genhain** [Flinesoft/BartyCrouch#115] opened 2019-02-15 11:42 UTC
Im using the library [Localize-Swift](https://github.com/marmelroy/Localize-Swift) to do localisation and the syntax is something akin to

`"Hello world".localized()` 

And i attempted to change the [update.code] customFunction to = `"localized"` and any other variation i could think of, but to no avail and my suspicion is that it's looking from something in the format 
`SuperSpecialLocalizationThingDooDad("Hello world")` Is there any way to get your library and [Localize-Swift](https://github.com/marmelroy/Localize-Swift) to play nicely with one another?

here is my `bartycrouch.toml`
```.swift
[update]
tasks = ["interfaces", "code", "transform", "normalize"]

[update.interfaces]
path = "/Users/benfowler/Developer/checkin-ios/Checkin"
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false

[update.code]
customFunction = "localized"
codePath = "/Users/benfowler/Developer/checkin-ios/Checkin"
localizablePath = "."
defaultToKeys = false
additive = true
unstripped = false

[update.transform]
codePath = "."
localizablePath = "."
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
path = "/Users/benfowler/Developer/checkin-ios/Checkin"
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "/Users/benfowler/Developer/checkin-ios/Checkin"
duplicateKeys = true
emptyValues = true

```

**Comment by Dschee** [comment] 2019-02-15 12:38
This is a duplicate of #47, see [my comment](https://github.com/Flinesoft/BartyCrouch/issues/47#issuecomment-271904843) there.

Localize-Swift states in their own README that they need a custom genstrings script and can't use the normal `genstrings` (or the new `extractLocString`) script from Apple. Also, Localize-Swift doesn't use the Apple way of localizing things which is out of scope of this library. I wonder what you wanted to use BartyCrouch for in the first place? You could still use the "interfaces" task.

**Closed by Dschee** 2019-02-15 12:38 UTC

**Comment by Genhain** [comment] 2019-02-16 21:09
@Dschee Ah i see, well BartyCrouch just does that little bit more than Localize-Swift and i was just hoping to get a bit of best of "both worlds" as such, It would also help as i work abroad and our QA does the translations and i was trying to set it up so they just had to run a few commands and it would do most the work for them.

In any case thank you
