### ISSUE TITLE
Illegal instruction: 4  bartycrouch lint -x

### ISSUE THREAD

**Issue by swebal** [Flinesoft/BartyCrouch#154] opened 2019-11-11 09:24 UTC
Happens every time I build. I have to perform a clean build folder before building in order to run the app. Any Ideas what is causing it? Bartycrouch installed via Homebrew, Xcode 11.1.

/Users/xxxxx/xxxxx/xxxxx/xxxxx/Build/Intermediates/xxxxx.build/Debug-iphoneos/xxxxx.build/Script-61962FBF23631A6400AC3F60.sh: line 7: 34489 Illegal instruction: 4  bartycrouch update -x
/Users/xxxxx/xxxxx/xxxxx/xxxxx/Build/Intermediates/xxxxx.build/Debug-iphoneos/xxxxx.build/Script-61962FBF23631A6400AC3F60.sh: line 7: 34527 Illegal instruction: 4  bartycrouch lint -x
Command PhaseScriptExecution failed with a nonzero exit code

Scrip I'm running in build phases:

```
if which bartycrouch > /dev/null; then
    bartycrouch update -x
    bartycrouch lint -x
else
    echo "warning: BartyCrouch not installed, download it from https://github.com/Flinesoft/BartyCrouch"
fi
```

**Comment by kcw-grunt** [comment] 2019-11-27 20:02
@swebal   I would check the order

**Comment by Jeehut** [comment] 2019-11-30 07:55
Can you provide the following info please as this doesn't happen to me:

1. Which macOS version are you using?
2. What version do you get when running `brew upgrade`?
3. What version of Swift / Xcode do you have installed? (`swift -version`, `xcodebuild -version`)
4. Does your full path to the project contain whitespaces?

Which macOS version are you using?

**Comment by swebal** [comment] 2019-12-20 11:02
Answer to @kcw-grunt 
The order in Build Phases is the following:
1. Dependencies
2. Run Script
3. Compile sources (22 items)
4. Link binary with libraries (0 items)
5. Copy bundle resources (13 items)

Answers to @Jeehut 
1. MacOS Catalina, 10.15.1
2. Doesn't list version, but there was an error during upgrade which I fixed with brew doctor and added a folder, then upgrade went ok.
3. Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
Target: x86_64-apple-darwin19.0.0
Xcode 11.2.1
Build version 11B53
4.No whitespaces

Sorry for the late reply, thanks for any help!

**Comment by kamil-buczel** [comment] 2020-02-28 13:23
Any news? I get same error, both for xcode and console

**Comment by Jeehut** [comment] 2020-02-28 14:16
@swebal @kamil-buczel Hmm, unfortunately I can't reproduce this. I don't see any weird things in the environment from the info posted by @swebal so I suppose it's a project configuration issue. Could you maybe provide a minimal project on GitHub where this issue is happening for you guys so I can investigate more and maybe reproduce it that way? If it's a project configuration problem, then I can fix it that way.

**Comment by kamil-buczel** [comment] 2020-02-28 14:30
@Jeehut I confirm, it seems to be configuration issue. Xcode Project structure changed to contain directories with folders, instead of just standard directories which caused Localizable files to be held in wrong place (not one that .toml file is pointing to). 

I was a bit surprised that there was not an error saying "missing file" or a "bad configuration" tbh 
Same when .toml file is nested - it seems to use default .toml file and do not print a warning about it (?)

IMO topic can be closed.

**Comment by Jeehut** [comment] 2020-02-28 14:52
@kamil-buczel Sorry but I didn't understand, could you find a way to work around this issue? If yes, could you please explain to help out others who might come across this. Also, I didn't understand the problem, isn't there a way we can fix this within BartyCrouch? If yes, how?

**Comment by kamil-buczel** [comment] 2020-03-02 07:06
Sorry if my response was too chaotic ;)

The issue seems to be related to bad configuration of the project; paths in .bartycrouch.toml file weren't filled correctly eg. instead of 

`[update.transform]
codePath = "project/"
localizablePath = "project/SupportingFiles/"
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"`


there was

`[update.transform]
codePath = "dog/"
localizablePath = "project/UtilFiles/"
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"`

As for bartycrouch; instead of displaying some info like "Missing path" or "wrong configuration: it only errored out with `Illegal instruction: 4` :) Hope that explains it!

**Comment by Jeehut** [comment] 2020-04-16 07:04
Thanks, I understand now. When there's no configuration file, then BartyCrouch runs with the default configuration. In your case, the `Illegal instruction: 4` was probably shown because the default configuration was considering too many files and in some of them, there was an issue. To fix that error, we would need to know what the actual problem was, so feel free to open a new issue with a Demo project where I can reproduce the error. But as far as this issue goes, I think we can close it as you already suggested.

**Closed by Jeehut** 2020-04-16 07:04 UTC
Labels: help wanted

**Comment by heavensword** [comment] 2020-05-22 03:30
I encounter the same problem. How to fix it?

**Comment by Jeehut** [comment] 2020-05-23 05:57
@heavensword Can you please provide more info like the version of BartyCrouch you're using and your config file?

**Comment by heavensword** [comment] 2020-05-26 06:58
Thanks~, my Project Swift version is 4. I guess this is the reason.I will try to upgrade the swift version used in the project.
