### ISSUE TITLE
Normalize: How do we prevent "Removing unnecessary keys"?

### ISSUE THREAD

**Issue by guidedways** [Flinesoft/BartyCrouch#202] opened 2020-09-24 23:00 UTC
## Expected Behavior
This is my current configuration, I expect `harmonizeWithSource` to not remove any key it thinks is unnecessary.
```
[update.normalize]
paths = ["./strings", "./resources"]
sourceLocale = "en"
harmonizeWithSource = false
sortByKeys = true
```

## Actual Behavior
Removing keys from Localization.strings

**Comment by Jeehut** [comment] 2020-10-06 02:35
Duplicate of #197.

**Closed by Jeehut** 2020-10-06 02:35 UTC
Labels: bug
