### ISSUE TITLE
NSLocalizedString keep geetting removed from the .strings files

### ISSUE THREAD

**Issue by MaksOta** [Flinesoft/BartyCrouch#122] opened 2019-03-14 08:41 UTC
I require some assistance 

No matter how i try to set up the project, the strings that come from NSLocalizedString() are removed and re-added every time i build the project. Can you see if i am doing something wrong?
Other strings that come from the storyboard are working fine. 

This is my .toml file. I tried changing all kinds of settings but the issue persists.
```
[update]
tasks = ["interfaces", "code", "normalize"]

[update.interfaces]
path = "."
defaultToBase = true
ignoreEmptyStrings = false
unstripped = true

[update.code]
codePath = "."
localizablePath = "."
defaultToKeys = true
additive = true
unstripped = true
customLocalizableName = "Main"

[update.transform]
codePath = "."
localizablePath = "."
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
path = "."
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "."
duplicateKeys = true
emptyValues = true
```

In swift i have things like
```swift
if (bookAuthorField.text?.isEmpty)! {
            bookAuthorField.hasError = true
            bookAuthorField.errorMessage.text = NSLocalizedString("authorFieldErrorMessage", value: "Author is required", comment: "Author is required")
            return
        }
```

which in the .strings files correctly gives me
```
/* Author is required */
"authorFieldErrorMessage" = "Author is required";
```

But then if i rebuild again the string is just refreshed even if i translate.
I am attaching also how my storyboard / .strings files are setup in case it has something to do with that.
![Screenshot 2019-03-14 at 09 38 30](https://user-images.githubusercontent.com/17080408/54342523-f4c45380-463c-11e9-9b71-8b7fe93e89c6.png)

I also tried with the transform task but in that case the translation string weren't event added to the .strings files but the swift code was replaced.

Let me know if you require more information
Thanks for the help

**Comment by MaksOta** [comment] 2019-03-19 07:50
I have tried using the 
```
NSLocalizedString("titleFieldErrorMessage", tableName: "Code", value: "Title is required", comment: "Title is required")
```
and setting `customLocalizableName = "Code"` in my .toml file but now the update command no longer extracts the strings from the code automatically. I have to put the new strings into the english Code.strings and then it copies over to other languages for me atleast.

I must be doing something wrong but i just can't figure out what...

**Comment by Dschee** [comment] 2019-03-19 17:12
Do you have a `Localizable.strings` file in your project? Or why did you only show the Main.storyboard file with its own Strings files? Please note that `NSLocalizedString` entries from code shouldn't be placed into the Strigns files of a storyboard. If that happens, then this is a bug.

Other than that, youc config looks fine (looks like the default config) and the `additive = true` flag should ensure that when you change your translation it is not added again. Only Storyboards have some extra logic to update, but that should have nothing to do with the Localizable.strings file.

Could you please give more information about your project structure? Best would be to have some sample project where I could have a look at this. You could for example remove all code files and send me the project to github@cihatguenduez.de so I can elaborate the isseu.

**Comment by MaksOta** [comment] 2019-03-20 15:26
Does it have to be named `Localizable.strings`? My understanding with `customLocalizableName = "Code"` is the the file can be named anything. "Code.strings" in this case

**Comment by Dschee** [comment] 2019-03-20 17:03
Yes, that's right. I just wanted to make sure you don't expect the code Strings references to be added to the Main.strings file of your Main.storyboard, but Code.strings should be fine.

**Comment by MaksOta** [comment] 2019-03-22 13:12
Aha, i had my customLoclizableName set to "Main" because i thought i could just have everything in one file.
But now I created a Code.string in my Storyboards folder. And set customLocalizableName = Code in .toml. But when i run the update i get:
`
Starting Task 'Update Interfaces' ...
2019-03-22 14:09:45.272: ✅  ./Kobi/Storyboards/Base.lproj/LaunchScreen.storyboard:  Successfully updated strings file(s) of Storyboard or XIB file.
2019-03-22 14:09:46.393: ℹ️  Incrementally updated keys of file '/Users/mask/Projects/xcode/Kobi/Kobi/Storyboards/en.lproj/Main.strings'.
2019-03-22 14:09:46.514: ℹ️  Incrementally updated keys of file '/Users/mask/Projects/xcode/Kobi/Kobi/Storyboards/es.lproj/Main.strings'.
2019-03-22 14:09:46.623: ℹ️  Incrementally updated keys of file '/Users/mask/Projects/xcode/Kobi/Kobi/Storyboards/sl.lproj/Main.strings'.
2019-03-22 14:09:46.751: ℹ️  Incrementally updated keys of file '/Users/mask/Projects/xcode/Kobi/Kobi/Storyboards/nl.lproj/Main.strings'.
2019-03-22 14:09:46.751: ✅  ./Kobi/Storyboards/Base.lproj/Main.storyboard:  Successfully updated strings file(s) of Storyboard or XIB file.
Task 'Update Interfaces' took 7.967 seconds.
Starting Task 'Update Code' ...
2019-03-22 14:09:48.232: ⚠️  No localizations extracted from Code in directory '.'.
Task 'Update Code' took 1.479 seconds.
Starting Task 'Normalize' ...
Task 'Normalize' took 0.596 seconds.
`
And no new strings are added to Code.strings.

**Comment by Dschee** [comment] 2019-03-25 09:32
Looks like it couldn't find any `NSLocalizedString` calls within the provided path. According to your setting the path is set to `.` which would mean, all files recursively within the current directory should be found. Are you sure you have such calls within the current directory? Could you also try to explicitly specify a code path like `Sources` like recommended in the first point within the Configuration section in the README [here](https://github.com/Flinesoft/BartyCrouch#configuration)?

If the issue still exists, please open a new issue and provide an example project where I can reproduce the issue so I can fix it. (Or fix it yourself and post a PR, if you have the time.)

I will close this issue though as the issue was actually misunderstanding in the features and not an actual issue.

**Closed by Dschee** 2019-03-25 09:32 UTC
